steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/ts-cloud-factory-poc/github.com/santosh-sahoo334/opencost-csv-export:${COMMIT_SHA}','.']
  env:
    - "DOCKER_BUILDKIT=1"
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/ts-cloud-factory-poc/github.com/santosh-sahoo334/opencost-csv-export:${COMMIT_SHA}']
timeout: 9000s
options:
 machineType: N1_HIGHCPU_32
#  Disk Size
 diskSizeGb: 50